config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  as :user do
    post 'signin' => 'devise/sessions#create'
    delete 'signout' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get '/share', to: 'movies#index'
  post '/share', to: 'movies#create'
  post '/vote', to: 'ratings#create'
  post '/unvote', to: 'ratings#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :ratings

  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  validates :url, presence: true, format: YT_LINK_FORMAT

  before_create :set_info_movie

  default_scope { order(created_at: :desc) }

  def set_info_movie
    id = Movie.get_youtube_id(self.url)
    movie = Movie.init_youtube(id)
    self.title = movie.title
    self.description = movie.description
    self.youtube_id = id
  end

  def self.init_youtube(id)
    return Yt::Video.new(id: id)
  end

  def self.get_youtube_id(url)
    regex_id = /^(?:https?:\/\/)?(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=)?([\w-]{10,})/
    match = regex_id.match(url)
    if match && !match[1].blank?
      match[1]
    else
      nil
    end
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  after_create :calculate_vote
  after_destroy :calculate_vote

  def calculate_vote
    ratings = Rating.where(movie_id: movie_id)
    vote_up = 0
    vote_down = 0
    ratings.each do |rating|
      vote_up += 1 if rating.is_voted_up
      vote_down += 1 if !rating.is_voted_up
    end
    movie = Movie.find_by_id(movie_id)
    movie.update(vote_up: vote_up, vote_down: vote_down)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable

  validates :email, presence: true

  has_many :movies
  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.all.includes(:ratings).page(params[:page]).per(5)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      flash[:notice] = "Share movie success!"
      redirect_to root_path
    else
      flash[:alert] = @movie.errors.full_messages.join(", ")
      render :index, status: :unprocessable_entity
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:url, :user_id)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :find_ratings, only: :destroy
  def create
    @rating = Rating.new(rating_params)
    respond_to do |format|
      if @rating.save
        format.html { redirect_to root_path}
      else
        format.html { render json: {status: :unprocessable_entity}}
      end
    end
  end

  def destroy
    respond_to do |format|
      if @ratings.destroy_all
        format.html { redirect_to root_path }
        format.json { render json: @ratings }
      else
        format.json { render json: {status: :unprocessable_entity}}
      end
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:user_id, :movie_id, :is_voted_up)
  end

  def find_ratings
    @ratings = Rating.where(user_id: params[:user_id], movie_id: params[:movie_id])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :check_user_exists, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
  end

  protected

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end

  def build_resource(hash = {})
    self.resource = resource_class.new_with_session(hash, session)
  end

  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end

  private

  def check_user_exists
    user = User.find_by(email: params[:user][:email])
    unless user.present?
      build_resource(sign_up_params)

      resource.save
      yield resource if block_given?
      if resource.persisted?
        if resource.active_for_authentication?
          set_flash_message! :notice, :signed_up
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource) if is_navigational_format?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-8 col-md-8 mx-auto">
        <% @movies.each do |movie| %>
          <div class="row my-5">
            <div class="col-6">
              <div class="embed-responsive embed-responsive-4by3 h-100">
                <iframe class="embed-responsive-item h-100 w-100" src="//www.youtube.com/embed/<%= movie.youtube_id %>"></iframe>
              </div>
            </div>
            <div class="col-6 text-start">
              <a href="<%= movie.url %>" class="my-2"><%= movie.title %></a>
              <div class="d-flex my-2 justify-content-between align-items-center">
                Shared by: <%= movie.user.email %>
                <% if current_user.present? %>
                  <div class="d-flex flex-row">
                    <% if movie.ratings.where(user_id: current_user).count == 0 %>
                      <%= link_to vote_path(rating: {user_id: current_user, movie_id: movie.id, is_voted_up: true}), class: "btn btn-link btn-thumbs", data: {"turbo-method": :post} do %>
                        <%= image_tag "/images/thumbs-up.svg" %>
                      <% end %>
                      <%= link_to vote_path(rating: {user_id: current_user, movie_id: movie.id, is_voted_up: false}), class: "btn btn-link btn-thumbs", data: {"turbo-method": :post} do %>
                        <%= image_tag "/images/thumbs-down.svg" %>
                      <% end %>
                    <% end  %>

                    <% if movie.ratings.where(user_id: current_user, is_voted_up: true).count > 0 %>
                      <%= link_to unvote_path(user_id: current_user, movie_id: movie.id), class: "btn btn-link btn-thumbs unvote", data: {"turbo-method": :post} do %>
                        <%= image_tag "/images/thumbs-up.svg" %>
                      <% end %>
                    <% end %>

                    <% if movie.ratings.where(user_id: current_user, is_voted_up: false).count > 0 %>
                      <%= link_to unvote_path(user_id: current_user, movie_id: movie.id), class: "btn btn-link btn-thumbs unvote", data: {"turbo-method": :post} do %>
                        <%= image_tag "/images/thumbs-down.svg" %>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <div class="widget w-100 text-start my-2">
                <div class="upvote thumbs">
                  <div>
                    <span class="vote-up-number">
                      <%= movie.vote_up %>
                    </span>
                    <%= image_tag "/images/thumbs-up.svg" %>
                  </div>
                </div>
                <div class="downvote thumbs">
                  <div>
                    <span class="vote-down-number">
                      <%= movie.vote_down %>
                    </span>
                    <%= image_tag "/images/thumbs-down.svg" %>
                  </div>
                </div>
              </div>
              <div class="my-2">Description:</div>
              <div class="my-2"><%= truncate(movie.description.html_safe, length: 200) %></div>
            </div>
          </div>
        <%  end %>
        <%= paginate @movies %>
      </div>
    </div>
  </section>
</main>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">Funny Movie</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-row-reverse" id="navbarNavDropdown">
      <% if current_user.present? %>
        <%= link_to 'Sign out', destroy_user_session_path, class: "btn btn-light ms-3", data: {"turbo-method": :delete} %>
        <%= link_to 'Share a movies', share_path, class: "btn btn-warning ms-3" %>
        <span class="text-white">Welcome <%= current_user.email %></span>
      <% else %>
        <%= form_for(:user, :url => session_path(:user), html: {class: 'd-flex'}) do |f| %>
          <div class="input-group">
            <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
          </div>
          <div class="input-group ms-3">
            <%= f.password_field :password, class: "form-control" %>
          </div>
          <%= f.submit "Login / Register", class: "btn btn-light ms-3" %>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemitanoProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice.present? %>
      <div id="flash" class="notice"><%= notice %></div>
    <% end  %>

    <% if alert.present? %>
      <div id="flash" class="alert"><%= alert %></div>
    <% end  %>
    <%= render partial: "/layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<main>
  <section class="py-5 text-center container">
    <div class="card w-50 m-auto">
      <div class="card-header">
        Share a youtube movie
      </div>
      <div class="card-body row">
        <p class="col-3 card-text">Youtube URL:</p>
        <div class="col-6">
          <%= form_for :movie, html: {id: "new_movie"} do |f| %>
            <div class="input-group mb-3">
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.text_field :url, class: 'form-control', placeholder: "Youtube url" %>
            </div>
            <%= f.submit "Share", class: "btn btn-primary d-block w-100" %>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</main>